#!/bin/bash

set -e

tests=(
    alias_args
    alias_getelementptr
    alias_inttoptr
    arithmetic
    casting
    circular_call_1
    circular_call_2
    div
    escape_arg
    escape_global
    getelementptr_1
    getelementptr_2
    getelementptr_3
    getelementptr_4
    global_values
    indirect_call
    inline_alloca
    irreducible_cfg
    load_uninitialized
    many_args
    many_regs
    many_regs_large_stack_frame
    mul
    phi_lost_copy
    phi_swap
    poison
    relational
    rem
    select
    select_ptr
    self_loop
    self_reference
    store_ptr
    tail_call_alloca
    type_punning
    unreachable_block_1
    unreachable_block_2

    accumulate
    base64
    bfs
    bit
    bubble_sort
    dfs
    dijkstra_shortest_paths
    edit_distance
    exgcd
    fibonacci
    floyd_warshall_all_pairs_shortest_paths
    gaussian_elimination
    gcd
    gcd_iterative
    hanoi
    heapsort
    insertion_sort
    is_prime
    linear_regression
    matmul
    max
    mergesort
    n_queens
    partition_function
    pcg32
    power
    quicksort
    selection_sort
    sieve_of_eratosthenes
    splitmix64
    sum
    tarjan_strongly_connected_components
    topological_sort
    xorshift32
    xorshift64
)

for test_name in "${tests[@]}"; do
    echo "$test_name"
done
