name: build-mips64-linux

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        build-type: [Debug, Release]
      fail-fast: false
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y g++-14-mips64-linux-gnuabi64 gcc-14-riscv64-linux-gnu qemu-user
          sudo mkdir -p /usr/gnemul
          sudo ln -s /usr/mips64-linux-gnuabi64 /usr/gnemul/qemu-mips64
          sudo ln -s /usr/riscv64-linux-gnu /usr/gnemul/qemu-riscv64

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - run: |
          cmake \
            -B ${{ github.workspace }}/build \
            -DCMAKE_BUILD_TYPE="${{ matrix.build-type }}" \
            -DCMAKE_SYSTEM_NAME="Linux" \
            -DCMAKE_SYSTEM_PROCESSOR="mips64" \
            -DCMAKE_CXX_COMPILER="mips64-linux-gnuabi64-g++-14" \
            -DCMAKE_CROSSCOMPILING_EMULATOR="qemu-mips64" \
            -DMINI_LLVM_TESTS=ON \
            -G Ninja

      - run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

      - run: ctest --test-dir ${{ github.workspace }}/build --build-config ${{ matrix.build-type }}

      - working-directory: ${{ github.workspace }}/tests/tools/mini-llc
        run: |
          export MINI_LLC_COMMAND="qemu-mips64 ${{ github.workspace }}/build/tools/mini-llc/mini-llc"
          export LINKER_COMMAND="riscv64-linux-gnu-gcc-14"
          export EMULATOR_COMMAND="qemu-riscv64"
          export DIFF_COMMAND="diff"
          export MINI_LLC_TIMEOUT=60
          export LINKER_TIMEOUT=60
          export EMULATOR_TIMEOUT=60
          ./test-all.sh --target=riscv64
