name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:24.04

    strategy:
      matrix:
        config: [Debug, Release]
        compiler: [g++, clang++]
        sanitizer: ['', -fsanitize=address, -fsanitize=undefined]
        shared: ['OFF', 'ON']

      fail-fast: false

    defaults:
      run:
        shell: bash

    env:
      GCC_VERSION: '15'
      LLVM_VERSION: '22'
      BOOTLIN_TOOLCHAIN_VERSION: 'stable-2025.08-1'

    steps:
      - run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential curl file git procps

      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - run: chown -R $(whoami):$(whoami) .

      - uses: ./.github/actions/setup-homebrew

      - if: ${{ matrix.compiler == 'g++' }}
        uses: ./.github/actions/setup-toolchain
        with:
          install-gcc: 'true'
          gcc-version: ${{ env.GCC_VERSION }}

      - if: ${{ matrix.compiler == 'clang++' }}
        uses: ./.github/actions/setup-toolchain
        with:
          install-gcc: 'true'
          gcc-version: ${{ env.GCC_VERSION }}
          install-llvm: 'true'
          llvm-version: ${{ env.LLVM_VERSION }}
          clang-use-gcc-libstdcxx: 'true'

      - run: brew install cmake ninja

      - run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE="${{ matrix.config }}" \
            -DCMAKE_CXX_COMPILER="${{ matrix.compiler }}" \
            -DCMAKE_CXX_FLAGS="${{ matrix.sanitizer }}" \
            -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.sanitizer }}" \
            -DCMAKE_SHARED_LINKER_FLAGS="${{ matrix.sanitizer }}" \
            -DCMAKE_MODULE_LINKER_FLAGS="${{ matrix.sanitizer }}" \
            -DBUILD_SHARED_LIBS="${{ matrix.shared }}" \
            -DMINI_LLVM_TESTS=ON \
            -G Ninja

      - run: cmake --build build

      - env:
          UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
        run: ctest --test-dir build --output-on-failure

      - run: brew install qemu

      - id: install-riscv64-toolchain
        uses: ./.github/actions/setup-bootlin-toolchain
        with:
          toolchain: riscv64-lp64d--glibc--${{ env.BOOTLIN_TOOLCHAIN_VERSION }}

      - env:
          UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
        run: |
          for allocator in graph-coloring linear-scan naive; do
            echo "Testing register allocator: $allocator"
            QEMU_LD_PREFIX="${{ steps.install-riscv64-toolchain.outputs.dest }}/riscv64-buildroot-linux-gnu/sysroot" \
              ./tests/mini-llc/test_all.sh \
              --mini-llc "./build/bin/mini-llc --register-allocator $allocator" \
              --target riscv64 \
              --driver "${{ steps.install-riscv64-toolchain.outputs.dest }}/bin/riscv64-buildroot-linux-gnu-gcc" \
              --emulator qemu-riscv64
          done

  build-linux-bazel:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:24.04

    strategy:
      matrix:
        compilation_mode: ['fastbuild', 'dbg', 'opt']
        shared: ['false', 'true']

      fail-fast: false

    defaults:
      run:
        shell: bash

    env:
      GCC_VERSION: '15'
      BAZEL_VERSION: '9'

    steps:
      - run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential curl file git procps

      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - run: chown -R $(whoami):$(whoami) .

      - uses: ./.github/actions/setup-homebrew

      - uses: ./.github/actions/setup-toolchain
        with:
          install-gcc: 'true'
          gcc-version: ${{ env.GCC_VERSION }}

      - run: |
          brew install bazel@${{ env.BAZEL_VERSION }}
          brew link -f bazel@${{ env.BAZEL_VERSION }}

      - run: |
          CC=gcc CXX=g++ bazel build \
            --action_env=PATH=/home/linuxbrew/.linuxbrew/bin:/bin:/usr/bin:/usr/local/bin \
            --compilation_mode=${{ matrix.compilation_mode }} \
            --//:shared=${{ matrix.shared }} \
            //:mini-llvm \
            //tools/mini-llc:mini-llc \
            //unittests:unittests

      - run: |
          CC=gcc CXX=g++ bazel test \
            --action_env=PATH=/home/linuxbrew/.linuxbrew/bin:/bin:/usr/bin:/usr/local/bin \
            --compilation_mode=${{ matrix.compilation_mode }} \
            --//:shared=${{ matrix.shared }} \
            //unittests:unittests

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        config: [Debug, Release]
        shared: ['OFF', 'ON']

      fail-fast: false

    defaults:
      run:
        shell: bash

    env:
      GCC_VERSION: '15'

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE="${{ matrix.config }}" \
            -DCMAKE_CXX_COMPILER="/opt/homebrew/opt/gcc@$GCC_VERSION/bin/g++-$GCC_VERSION" \
            -DBUILD_SHARED_LIBS="${{ matrix.shared }}" \
            -DMINI_LLVM_TESTS=ON \
            -G Ninja

      - run: cmake --build build

      - run: ctest --test-dir build --output-on-failure

  build-windows:
    runs-on: windows-2025

    strategy:
      matrix:
        config: [Debug, Release]
        shared: ['ON', 'OFF']

      fail-fast: false

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - run: |
          cmake ^
            -S . ^
            -B build ^
            -DBUILD_SHARED_LIBS=${{ matrix.shared }} ^
            -DMINI_LLVM_TESTS=ON ^
            -G "Visual Studio 17 2022"

      - run: cmake --build build --config ${{ matrix.config }}

      - run: ctest --test-dir build --build-config ${{ matrix.config }} --output-on-failure
