name: check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ${{ github.workspace }}/contrib/format_all.sh --check
