name: docs

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:24.04

    defaults:
      run:
        shell: bash

    env:
      GCC_VERSION: '15'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential curl file git procps

      - uses: actions/checkout@v6
        with:
          submodules: 'true'

      - run: chown -R $(whoami):$(whoami) .

      - uses: ./.github/actions/setup-homebrew

      - uses: ./.github/actions/setup-toolchain
        with:
          install-gcc: 'true'
          gcc-version: ${{ env.GCC_VERSION }}

      - run: brew install cmake doxygen graphviz ninja

      - run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DMINI_LLVM_DOCS=ON \
            -G Ninja

      - run: cmake --build build --target docs

      - uses: actions/upload-pages-artifact@v5
        with:
          path: ./build/html

      - id: deployment
        uses: actions/deploy-pages@v5
